=== Luisa-GVR/XML_Desarrollo/DTD.dtd
<!-- Fecha partido-->
<!ELEMENT fecha (#PCDATA)>

<!-- Equipo 1-->
<!ELEMENT equipo1 (equipo, marcador)>

<!-- Equipo 2-->
<!ELEMENT equipo2 (equipo, marcador)>


<!ELEMENT equipo EMPTY>
<!ATTLIST equipo
        local  (si|no) #REQUIRED
        ganador (si|no|empate) #IMPLIED
        nombre CDATA #REQUIRED
        >

<!-- Marcador final-->
<!ELEMENT marcador (#PCDATA)>

<!ELEMENT jugador (#PCDATA)>
<!ATTLIST jugador
        nombre CDATA #REQUIRED
        numero CDATA #REQUIRED
        >

<!-- Jugadores que anotaron y el minuto-->
<!ELEMENT anotar (anotarInfo, jugador)*>
<!ATTLIST anotarInfo
        minuto CDATA #REQUIRED
        equipo CDATA #REQUIRED
        >
<!ELEMENT anotarInfo EMPTY>

<!ELEMENT partido (fecha, equipo1, equipo2, anotar*)>

=== Luisa-GVR/XML_Desarrollo/XML.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE partido SYSTEM "DTD.dtd">
<partido>
    <fecha>24-09-2023</fecha>

    <equipo1>
        <equipo local="si" ganador="empate" nombre="Toluca"/>
        <marcador>1</marcador>
    </equipo1>

    <equipo2>
        <equipo local="no" ganador="empate" nombre="América"/>
        <marcador>1</marcador>
    </equipo2>

    <anotar>
        <anotarInfo minuto="25" equipo="América"/>
        <jugador nombre="Diego Valdés" numero="10"/>
    </anotar>
    <anotar>
        <anotarInfo minuto="54" equipo="Toluca"/>
        <jugador nombre="Maximiliano Araujo" numero="11"/>
    </anotar>

</partido>
